import {
  AlertCircle,
  AlertTriangle,
  ArrowRight,
  ArrowUpRight,
  Ban,
  Bell,
  Bot,
  Briefcase,
  Building2,
  Calendar,
  Car,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleDollarSign,
  Clock,
  CreditCard,
  Droplet,
  FileText,
  Hammer,
  Home,
  Inbox,
  Info,
  LayoutDashboard,
  ListChecks,
  Loader2,
  LogOut,
  MapPin,
  Menu,
  MessageSquare,
  Minimize2,
  Monitor,
  Moon,
  Pencil,
  Phone,
  Plus,
  Printer,
  Receipt,
  RefreshCw,
  Scissors,
  Search,
  Send,
  Settings2,
  ShieldCheck,
  Sparkles,
  Star,
  Sun,
  Trash2,
  Truck,
  TrendingUp,
  User,
  Users,
  Wifi,
  Wrench,
  X,
  Zap
} from 'lucide-react';

// Icon registry: maps short semantic names (used across the app) to lucide
// components. <Icon name="..."/> resolves here and falls back to Wrench when
// the name is unknown, so a typo never crashes a screen.
export const ICONS = {
  alert: AlertTriangle,
  alertcircle: AlertCircle,
  arrowright: ArrowRight,
  arrowupright: ArrowUpRight,
  ban: Ban,
  bell: Bell,
  bot: Bot,
  briefcase: Briefcase,
  building: Building2,
  calendar: Calendar,
  car: Car,
  check: Check,
  checkcircle: CheckCircle2,
  chevronleft: ChevronLeft,
  chevronright: ChevronRight,
  'chevron-down': ChevronDown,
  clock: Clock,
  dashboard: LayoutDashboard,
  dollar: CircleDollarSign,
  droplet: Droplet,
  edit: Pencil,
  file: FileText,
  hammer: Hammer,
  home: Home,
  inbox: Inbox,
  info: Info,
  list: ListChecks,
  loader: Loader2,
  logout: LogOut,
  mappin: MapPin,
  menu: Menu,
  messagesquare: MessageSquare,
  minimize: Minimize2,
  monitor: Monitor,
  moon: Moon,
  phone: Phone,
  plus: Plus,
  printer: Printer,
  receipt: Receipt,
  refresh: RefreshCw,
  scissors: Scissors,
  search: Search,
  send: Send,
  settings: Settings2,
  shield: ShieldCheck,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  trash: Trash2,
  trending: TrendingUp,
  truck: Truck,
  user: User,
  users: Users,
  wifi: Wifi,
  wrench: Wrench,
  x: X,
  zap: Zap,
  card: CreditCard,
  invoice: Receipt
};

// Renders an icon by registry name; extra props (size, aria-hidden, …) are
// forwarded to the underlying lucide component.
export default function Icon({ name, size = 20, className = '', strokeWidth = 2, ...props }) {
  const Cmp = ICONS[name] || Wrench;
  return <Cmp size={size} className={className} strokeWidth={strokeWidth} {...props} />;
}
